-- require 'lspconfig'.lua_ls.setup {
--   on_init = function(client)
--     if client.workspace_folders then
--       local path = client.workspace_folders[1].name
--       if vim.uv.fs_stat(path .. '/.luarc.json') or vim.uv.fs_stat(path .. '/.luarc.jsonc') then
--         return
--       end
--     end
--
--     client.config.settings.Lua = vim.tbl_deep_extend('force', client.config.settings.Lua, {
--       runtime = {
--         -- Tell the language server which version of Lua you're using
--         -- (most likely LuaJIT in the case of Neovim)
--         version = 'LuaJIT'
--       },
--       -- Make the server aware of Neovim runtime files
--       workspace = {
--         checkThirdParty = false,
--         library = {
--           vim.env.VIMRUNTIME
--           -- Depending on the usage, you might want to add additional paths here.
--           -- "${3rd}/luv/library"
--           -- "${3rd}/busted/library",
--         }
--         -- or pull in all of 'runtimepath'. NOTE: this is a lot slower and will cause issues when working on your own configuration (see https://github.com/neovim/nvim-lspconfig/issues/3189)
--         -- library = vim.api.nvim_get_runtime_file("", true)
--       }
--     })
--   end,
--   settings = {
--     Lua = {}
--   },
-- }
-- require'lspconfig'.html.setup {
--   capabilities = capabilities,
-- }
--
-- require'lspconfig'.ts_ls.setup {
--   init_options = {
--     plugins = {
--       {
--         name = "@vue/typescript-plugin",
--         location = "/home/s-show/.nix-profile/bin/typescript-language-server",
--         languages = {"javascript", "typescript", "vue"},
--       },
--     },
--   },
--   filetypes = {
--     "javascript",
--     "javascriptreact",
--     "javascript.jsx",
--     "typescript",
--     "typescriptreact",
--     "typescript.tsx",
--     "vue",
--   },
-- }
--
-- require'lspconfig'.eslint.setup({})
-- require'lspconfig'.emmet_language_server.setup{}
-- -- Nix 言語の LSP 設定
-- -- LSP は `nil_ls`, Formatter は `nixfmt`.
-- require'lspconfig'.nil_ls.setup({
--   settings = {
--     ['nil'] = {
--       formatting = {
--         command = { "nixfmt" }
--       }
--     }
--   }
-- })
--
