-- [mini.aiで日本語の括弧の中身をrepeatableに編集する
-- Atusy's blog](https://blog.atusy.net/2024/11/27/mini-ai-ja/)
vim.keymap.set({ "x", "o" }, "ij[", "i?「<cr>」<cr>", { remap = true })
vim.keymap.set({ "x", "o" }, "aj[", "a?「<cr>」<cr>", { remap = true })
vim.keymap.set({ "x", "o" }, "ij<", "i?＜<cr>＞<cr>", { remap = true })
vim.keymap.set({ "x", "o" }, "aj<", "a?＜<cr>＞<cr>", { remap = true })
vim.keymap.set({ "x", "o" }, "ij{", "i?｛<cr>｝<cr>", { remap = true })
vim.keymap.set({ "x", "o" }, "aj{", "a?｛<cr>｝<cr>", { remap = true })
vim.keymap.set({ "x", "o" }, "ij(", "i?（<cr>）<cr>", { remap = true })
vim.keymap.set({ "x", "o" }, "aj(", "a?（<cr>）<cr>", { remap = true })
