-- local picker = require("snacks.picker")

vim.keymap.set('n', '<leader>sf', "<cmd>lua Snacks.picker.files({ hidden = true, })<CR>", { silent = true })
vim.keymap.set('n', '<leader>ss', "<cmd>lua Snacks.picker.smart()<CR>", { silent = true })
vim.keymap.set('n', '<leader>sp', "<cmd>lua Snacks.picker()<CR>", { silent = true })
vim.keymap.set('n', '<leader>sd', "<cmd>lua Snacks.dashboard()<CR>", { silent = true })
vim.keymap.set('n', '<leader>se', "<cmd>lua Snacks.explorer()<CR>", { silent = true })
vim.keymap.set('n', '<leader>sh', "<cmd>lua Snacks.picker.help()<CR>", { silent = true })
vim.keymap.set('n', '<leader>sf', "<cmd>lua Snacks.picker.files()<CR>", { silent = true })
vim.keymap.set('n', '<leader>sb', "<cmd>lua Snacks.picker.buffers()<CR>", { silent = true })
vim.keymap.set('n', '<leader>sg', "<cmd>lua Snacks.picker.grep({ hidden = true, })<CR>", { silent = true })
vim.keymap.set('n', '<leader>sc', "<cmd>lua Snacks.picker.command_history()<CR>", { silent = true })
