return {
  -- dir = '~/my_neovim_plugins/ft_mapper.nvim',
  's-show/ft-mapper.nvim',
  dev = false,
  opts = {
    debug = false,
    mappings = {
      { ',', '、', '，' },
      { '.', '。', '．' },
      { ":", "：" },
      { ";", "；" },
      { "!", "！" },
      { "?", "？" },
      { "(", "（" },
      { ")", "）" },
      { "[", "「", "『", "【", "［", "{", "｛" },
      { "]", "」", "』", "】", "］", "}", "｝" },
      { "'", "'", "'" },
      { '"', "“", "”", "゛" },
      { '<', "＜", "«" },
      { '>', "＞", "»" },
      { "-", "ー", "―", "—", "–" },
      { "~", "〜" },
      { "0", "０" },
      { "1", "１" },
      { "2", "２" },
      { "3", "３" },
      { "4", "４" },
      { "5", "５" },
      { "6", "６" },
      { "7", "７" },
      { "8", "８" },
      { "9", "９" },
      { " ", "　" }, -- 半角・全角スペース
    },
    -- no_default_mappings = true,
    line_limit = 10,
  },
  -- vim.keymap.set({ 'n', 'v', 'o' }, '<leader>f', '<Plug>(f_motion)'),
  -- vim.keymap.set({ 'n', 'v', 'o' }, '<leader>t', '<Plug>(t_motion)'),
  -- vim.keymap.set({ 'n', 'v', 'o' }, '<leader>F', '<Plug>(F_motion)'),
  -- vim.keymap.set({ 'n', 'v', 'o' }, '<leader>T', '<Plug>(T_motion)'),
  -- vim.keymap.set({ 'n', 'v', 'o' }, '>', '<Plug>(forward_repeat)'),
  -- vim.keymap.set({ 'n', 'v', 'o' }, '<', '<Plug>(backward_repeat)'),
}
